### ISSUE TITLE
TOTK crashes when closing any menu in the caves

### ISSUE THREAD

**Issue by AgentPotatoDev** [HolographicWings/TOTK-Mods-collection#100]
Hi, I have this problem where TOTK crashes in Yuzu when I close any menu in the caves, it also has random crashes and I don't understand the cause.

Specs:
GTX 1660 TI
i5 9400f
16GB DDR4
game on SSD

Mods installed:
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/65216658/eaa908fc-002b-437b-a47d-e95f6eacd0cc)
without the Yuzu fix the game wouldn't boot up. (stack in the loading screen)

Yuzu version:
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/65216658/5cf740fa-7cb4-4476-9dab-2d5bd4153b26)

**Comment by AgentPotatoDev** [comment]
Note, on any other Yuzu version I tried the game is stack on the Launching... screen.
for example in the newest version of yuzu: 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/65216658/49faa865-914e-4d87-af10-93c0c9244c01)

It is stack here:
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/65216658/1fceddd4-0ed3-4e41-992b-348fc85819b1)
Would like to get some much-needed help, thanks!

**Comment by Kneit0r** [comment]
Maybe try: https://github.com/pineappleEA/pineapple-src/releases

**Comment by AgentPotatoDev** [comment]
> Maybe try: https://github.com/pineappleEA/pineapple-src/releases

will try, thx

**Comment by SpockBauru** [comment]
You are using game version 1.0.0, these mods are for 1.1.1 or better.

**Comment by AgentPotatoDev** [comment]
I did all of the above, how do I check if there are mods who use the same file?

**Comment by AgentPotatoDev** [comment]
the only update I found is 1.1.2, I didn't check yet, just now remembered, later on, today when I have time I will check and report back, thank you for your time and dedication to helping me through this problem.

**Comment by AgentPotatoDev** [comment]
now it all works, thanks guys, only other problem , it is lagging in the lava area

**Comment by SpockBauru** [comment]
It will always lag in certain areas, there's nothing to do about it :'(
