### ISSUE TITLE
Full settings recommendations 

### ISSUE THREAD

**Issue by 02RIEGER20** [HolographicWings/TOTK-Mods-collection#101]
Hi guys , I have a **laptop** ASUS TUF Dash F15 with this specs:
RTX 3070 (8GB VRAM)
i5-11300H
24GB DDR4 3200Mhz
512gb SSD
so my question is which settings are recommended in YUZU emulator for this laptop , by settings i mean :
Game Version 
Update Version
All mods 
Emulation Settings:
Graphics settings 
Advanced Graphics settings
CPU

NOTE: please tell every single point because I want to play with decent resolution & graphics on stable 50-60fps 
and also if you want tell something additionally or u know YUZU very well u can contact me through discord (★尺工乇ム乇尺★#0161 or https://discord.gg/rDWqVzVX)

**Comment by 02RIEGER20** [comment]
> I have a system very similar to yours and I use the recommended settings here:
> 
> https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/SETUP.md#gh-dark-mode-only
> 
> and everything is quite flawless.
> 
> Concerning which build to use, most people would probably advocate for the latest EA build (Pineapple) since any issues are uncommon now, any new issues that pop up are quickly patched out usually, and the implementation rate for new features is quite rapid, which can lead to massive improvements in just a short period of time. You could use the mainline Yuzu build, but if you have any issues or are interested in any particular improvements, it will likely be some time before they are implemented compared to the EA builds.
> 
> As far as ATSC recompression, leave it uncompressed if you are going for 2x resolution since you have the VRAM for it, if you are going for 4x resolution, you will probably need BC3.
> 
> You should easily get 50-60 at 2x resolution since my system can, at 4x I don't think you would be able to push past 30-40.
> 
> You didn't mention your screen resolution, so it makes it a little harder to determine a good resolution for you. If you are 1080 or 1440p then 2x should be enough, if you're at 4K, you might want to push for 4x, despite the fact that you will have to settle for a lower FPS.
> 
> The only addition I would have to the list of mods on that page would be to include either SerFrost's Defogger:
> 
> https://gamebanana.com/mods/446995
> 
> or
> 
> Better Defog by Yakuzadeso
> 
> https://gamebanana.com/mods/447492
> 
> They're both good, so it's more a matter of taste than anything else.
> 
> As a general rule I like to use exefs type mods and implement RomFS mods either when there is no choice or it is necessary due to how the mod inherently needs to operate. The reason for this is that RomFS mods easily come into conflict with one another so how many you can implement at once is limited and they add lag to all your startup and any time you have to load a large amount of new data, such as teleporting. This has gotten much, much better in recent EA builds, but its still demonstrably slower. Whether that is an issue or not is up to each person.

Thank you so much brother ! 
My screen resolution is 1080 and what are your specs (if you want u can share if no , it's completely ok :))

**Comment by hoverbike1** [comment]
Game Version - Update to 1.1.1
Update Version - Update to 1.1.1 - this is the same as above.
All mods - Just use Lazy Patch 30 FPS 1080p X1, doubt a 11300H can run 60. Feel free to add a controller UI mod of your choice, as long as you use a UI Mod compatible lazy pack - check the end of their names.

Emulation Settings:
Graphics settings - 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/441fc03a-9e31-48ac-8249-795f6d327706)
Advanced Graphics settings - ![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/9b88dde5-35dc-411e-b2a1-8b65615683fe)
CPU - Set it to auto.
