### ISSUE TITLE
FPS - DynamicFPS++ - No Launch

### ISSUE THREAD

**Issue by Orbiiez** [HolographicWings/TOTK-Mods-collection#102]
When enabled FPS - DynamicFPS++ - Includes 60fps and DynamicFPS does not allow TOTK to launch, I tested by manually disabling every mod and re launching the game. I am running TOTK 1.1.2 and downloaded the correct folder for this version of the game yet still face this issue as well as the black screen when switching weapons or abilities even with the Fix and Xbox controllwe UI enabled

**Comment by SpockBauru** [comment]
Well, sometimes we need to nuke the Yuzu config...

Remove all mods except the update 1.1.2.
Reset Yuzu settings in Configure > "Reset All Settings" button.
Clear the cache by right click on the game name > Remove > "Remove All Pipeline Caches".
Clear the cache storage by right click on the game name > Remove > "Remove Cache Storage".
Restart your PC.
Start the game and wait a couple minutes to rebuild the shaders.

Only after that start installing mods. [Redownload the mods](https://github.com/HolographicWings/TOTK-Mods-collection/releases) and starting installing by the guide: https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/SETUP.md

**IMPORTANT: Make a backup of your save folder!**
Note: I'm on Yuzu mainline.

**Comment by Uranite** [comment]
Uninstall TOTK updates and reinstall it, works for me when I have issues of TOTK not launching
