### ISSUE TITLE
Cheats missing files and resolution mod missing from modpack as well

### ISSUE THREAD

**Issue by keatit71** [HolographicWings/TOTK-Mods-collection#103]
Cheats added to this modpack are missing the actual cheat files like infinite arrows and battery which only have the mod manager files and no cheats folder as well as oldmankain's 1080p mod being missing

**Comment by yogithesymbian** [comment]
one more is **zonai fan** is not infinity.

**Comment by yogithesymbian** [comment]
> one more is **zonai fan** is not infinity.

solved by using device dispencer first then its work . ( **its work only for new items after cheat activated** ) for my case . then when you fix this issue ? ( arrow infinity ? )

**Comment by SpockBauru** [comment]
Fixed on v2.0
