### ISSUE TITLE
there is no folder cheats for Infinite Arrows  (1.1.2) folder on v1.9.2.3

### ISSUE THREAD

**Issue by yogithesymbian** [HolographicWings/TOTK-Mods-collection#104]
pwd / path of folder : 
> `TOTK-Mods-collection_v1.9.2.3_for-1.1.2/Mods/Cheats/Infinite Arrows  (1.1.2)/`

#https://github.com/HolographicWings/TOTK-Mods-collection/releases/tag/v1.9.2.3
file : **TOTK-Mods-collection_v1.9.2.3_for-1.1.2.zip**

**Comment by roxasofthedark** [comment]
and in infinite battery

**Comment by SpockBauru** [comment]
It's a known issue. Please report your findings to https://github.com/HolographicWings/TOTK-Mods-collection/issues/103

**Comment by yogithesymbian** [comment]
so i will close issue cause duplicated #103
