### ISSUE TITLE
Steamdeck Aspect Ratio Doesn't work

### ISSUE THREAD

**Issue by roxasofthedark** [HolographicWings/TOTK-Mods-collection#105]
Been playing with it to try to get it to work without stretching. no avail.

**Comment by rollercoaster** [comment]
It is supposed to work with stretching enabled. UI is still wrong aspect but the game works fine at 16:10.

I used it on my Ayaneo 2 Handheld

**Comment by hoverbike1** [comment]
New Steam Deck Aspect Ratio arriving later this sunday, let me know if it solves your issues.
