### ISSUE TITLE
Sometimes the game doesn't process the interactions well with the mod on.

### ISSUE THREAD

**Issue by MasterVegito** [HolographicWings/TOTK-Mods-collection#110]
In Soryotanog Shrine in Gerudo Town the hidden chest is accessed by dusting off a large cog which then starts rotating opening the door. However, with DynamicFPS++_totk enabled, then door does not open. I temporarily had to disable the mod, to be able to complete the Shrine 100%. Just an FYI as I would not be surprised if it affects similar game mechanics in other locations.

**Comment by SpockBauru** [comment]
It's a known issue, ChucksFeedAndSeed is working on it and will be released with DynamicFPS 1.5.3. He is calling for beta testers if you are interested: https://www.reddit.com/user/ChucksFeedAndSeed/comments/143nsfu/
