### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by derbayer36** [HolographicWings/TOTK-Mods-collection#111]
Can you please add these mods from Nexus mod:

Custom Loading Screens - Dark mode:
https://www.nexusmods.com/legendofzeldatearsofthekingdom/mods/24

Better Fog (Not a Reshade)
https://www.nexusmods.com/legendofzeldatearsofthekingdom/mods/27

All credits go to the creators of these mods.

**Comment by ShuaBlue** [comment]
+1 for the better fog mod

**Comment by HyperDeltaa** [comment]
Custom Loading Screens mod doesn't work with aspect ratio mods, maybe a version merged with it? he even provides a tool for it https://github.com/Fruithapje21/TOTK-Ultrawide

**Comment by SpockBauru** [comment]
Custom Loading Screens is causing issues for many people, will not be added here.

On Better Fog page in NexusMods, If you read the "Permissions and Credits" section will see this paragraph: 
```
Upload permission
You are not allowed to upload this file to other sites under any circumstances
```
That's why none of these mods can be posted here.
