### ISSUE TITLE
Suggestion: Add a file to each mod folder that explains what the mod attempts to do

### ISSUE THREAD

**Issue by notoriousjere** [HolographicWings/TOTK-Mods-collection#114]

**Comment by HolographicWings** [comment]
Why ? the documentation is not enough ?

**Comment by notoriousjere** [comment]
I think it will add visibility when browsing the mods in a file explorer on your PC. There's so many mods and will probably be more to come. Not entirely necessary but I thought it could be a nice QOL thing.

**Comment by notoriousjere** [comment]
These files could be walked by a script to generate part of the readme to have the best of both worlds too

**Comment by AM800Max** [comment]
@notoriousjer what is your discord... I want to play with u (if you know what i mean hehe Pogchamp)

**Comment by SpockBauru** [comment]
Sorry, that's too much work for us. Best we can do is to try make the documentation up to date, and even so is being hard to do.
