### ISSUE TITLE
Game Stuck On Loading Screen

### ISSUE THREAD

**Issue by Thalacalibur01** [HolographicWings/TOTK-Mods-collection#115]
Whenever I put any mod in the mod data folder, the game goes to one frame on the loading screen when trying to load my last save and gets stuck.

**Comment by hoverbike1** [comment]
try redumping your game

**Comment by hoverbike1** [comment]
no, you delete that terrible pirate dump, and dump an actual one
you're not the first one to complain after using that same broken nsp.

https://yuzu-emu.org/help/quickstart/

**Comment by Thalacalibur01** [comment]
Alright, thanks.
