### ISSUE TITLE
Suggest For Mod Name Change

### ISSUE THREAD

**Issue by InfiniteParallel** [HolographicWings/TOTK-Mods-collection#116]
For the "[Disable Internal FSR downscaling" in "Graphics" I suggest that the name be changed to simply "Disable Internal FSR" as it doesn't just disable downscaling, it disables the shader sharpening function, as well as anything else the FSR function may do. This particular patch completely disables all aspects of Internal FSR entirely.

**Comment by hoverbike1** [comment]
The "Disable Internal FSR downscaling" patches **only** disable FSR scaling.
TOTK does not use an FSR sharpening filter, thus, it doesn't need to be disabled.
Relaying information from multiple modders I've asked this same question to.
