### ISSUE TITLE
Infinite durability doesnt work?

### ISSUE THREAD

**Issue by chromatic91** [HolographicWings/TOTK-Mods-collection#12]
I installed it just as shown, yet my weapons break, the mod is enabled... What could be wrong?

**Comment by HolographicWings** [comment]
> I installed it just as shown, yet my weapons break, the mod is enabled... What could be wrong?

Lot of cheats seems to don't work, i'm sorry, check here https://gamebanana.com/mods/games/7617 if theres is a better mod to do that, i'll test every cheat mod and remove the broken ones

Just before, do you play in 1.1.0 ? Maybe the memory address that the cheat patch change from the version.

**Comment by chromatic91** [comment]
> > I installed it just as shown, yet my weapons break, the mod is enabled... What could be wrong?
> 
> Lot of cheats seems to don't work, i'm sorry, check here https://gamebanana.com/mods/games/7617 if theres is a better mod to do that, i'll test every cheat mod and remove the broken ones
> 
> Just before, do you play in 1.1.0 ? Maybe the memory address that the cheat patch change from the version.

Yeah it's the 1.1.0 version. Thanks so much for the link, i looked at that website earlier but there's no mods to disable durability completely yet, it's just a matter of time though. Thanks so much for a quick response! Have a good day

**Comment by chromatic91** [comment]
Can confirm the mod above works well.

**Comment by akeryuuth** [comment]
Have you tried with the cheats listed in [this repo](https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom) ?
Could be what you're looking for, I personally don't use them so I can't tell you if it works for sure but they seem to be updated fairly frequently.

**Comment by chromatic91** [comment]
> Have you tried with the cheats listed in [this repo](https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom) ? Could be what you're looking for, I personally don't use them so I can't tell you if it works for sure but they seem to be updated fairly frequently.

No need, solved it above.
