### ISSUE TITLE
[Suggestion] Add a camera sensitivity mod

### ISSUE THREAD

**Issue by YosseufDEV** [HolographicWings/TOTK-Mods-collection#121]
Hello! I want to thank you for your great work as I wouldn't be able to play TOTK without your mods :) But a small issue that I don't seem to find a mod for is the camera sensitivity on yuzu as for me the camera is very slow for my preference I would like a mod that is like cemu BOTW mod with different options to increase sensitivity I found a mod but sadly isn't compatible for my version (1.0.0) and for the time being I can't update would appreciate it if you were able to create/port a mod for this issue

**Comment by hoverbike1** [comment]
has been added
will arrive with release of 2.2 this weekend
