### ISSUE TITLE
Update Aspect Ratio mods

### ISSUE THREAD

**Issue by Fruithapje21** [HolographicWings/TOTK-Mods-collection#122]
The Aspect Ratio mods have improved significantly since their initial release and are due for an update. Also the UI fixes for those aspect ratios should no longer be considered experimental / unstable. I am the original creator of all ultrawide patches. You can find my work here: https://github.com/Fruithapje21/TOTK-Ultrawide. I have also uploaded pre-patched version for some common aspect ratios here: https://github.com/Fruithapje21/TOTK-Ultrawide/tree/main/mods.

**Comment by Blitshunter** [comment]
No, I do not like these changes... They are crap like Joe biden. Trump is my Idol
Sincerely, Max

**Comment by hoverbike1** [comment]
copied the directory you linked, and added them, and used the script to generate new versions of the other aspect ratios we had.
thanks!
