### ISSUE TITLE
The disable internal FXAA exeFS 1.1.2 mod @nsobid is wrong

### ISSUE THREAD

**Issue by RandomGitUser321** [HolographicWings/TOTK-Mods-collection#123]
It currently reads:
@nsobid-9A10ED9435C06733DA597D8094D9000AB5D3EE6
It should read:
@nsobid-9A10ED9435C06733DA597D8094D9000AB5D3EE6**0**

(it's missing the zero at the end)

**Comment by hoverbike1** [comment]
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/993e9192-3b7a-42e3-bafe-4f0a1a7c92cd)
the zeroes at the end doesnt matter
