### ISSUE TITLE
Dynamic FPS still locked at 100 

### ISSUE THREAD

**Issue by lI-guy-Il** [HolographicWings/TOTK-Mods-collection#124]
- CPU : AMD 5950x
- GPU : Nvidia 3090 (NO OC)
- RAM : 32GB @ 2133 mhz (XMP is unstable, and I didn't bother to OC)
- Emulator : yuzu 1475
- API : Vulkan

As the title says, I cannot get the game to run faster that 100 fps, with either implementation of Dynamic FPS (++ or not). This is not a GPU bottleneck, its hovering at around 50% usage, (cpu at 15%). Just to make sure, I've tried *lowering* the render res to 0.5, and some thing. Hovering between 90 and 100 fps. Interestingly, menus don't have this issue.  Also, vsync options seem not to affect anything at all. 

Sidenote, is there a point to using resolution mods over/with the yuzu scaler? I'm running a 1440p monitor, so I'm a bit unsure of the setup. "cheat mode" 720p scaler at 4x (as antialiasing) seems worse than without the mod at 2x. 

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/61945175/fc58a65b-28ec-48d1-a302-2bb98e74c590)

**Comment by hoverbike1** [comment]
You'll probably find that you have cores that are being maxed out which are limiting you.
This is not an emulator as much as a hardware issue.

**Comment by lI-guy-Il** [comment]
You're right, though only one core is maxing. Odd. Is this normal behavior? 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/61945175/fb170a71-c81a-41e7-8e1c-0a03cc0727f6)

**Comment by hoverbike1** [comment]
yes, unfortunately, switch emulation requires a few (6-8) cores clocked as high as possible.

you might be able to tune your cpu for some better behavior, perhaps by parking the slower ccd and trying to get the single fastest ccd to run its cores at as high a clock as possible.
