### ISSUE TITLE
RE: Update Aspect ratio mods #122

### ISSUE THREAD

**Issue by Fruithapje21** [HolographicWings/TOTK-Mods-collection#126]
The new Aspect Ratio mods mentioned in #122 are only meant for ultrawide resolutions. The 16:10 mod is a special case: it that has been included in the mods folder, but can not be generated using the tool (which again is only for >16:9). The changes to the 1-1, 3-2, 4-3 and 5-4 mods should be reverted until there is proper support for these aspect ratios.

**Comment by hoverbike1** [comment]
done!
let me know what you think

**Comment by Fruithapje21** [comment]
Great! Probably should also update the readme to something along the lines of:

Aspect Ratio: Applies changes to the 3D scene render and UI elements to fit different aspect ratios
* Set "Aspect Ratio" in Graphics Yuzu settings to "Stretch to Window"
* Disable BlackscrenFix (already included)
* Incompatible with controller mods (can be merged using [custom tool](https://github.com/Fruithapje21/TOTK-Ultrawide))
* UI rescaling only works for 16:10 and ultrawide (>16:9) aspect ratios

**Comment by hoverbike1** [comment]
alright, should all be set and done now!
let me know if its all good with you

**Comment by Fruithapje21** [comment]
There is something wrong with the formatting of that section in the readme now. The rest is all good! Feel free to close this issue when the formatting is fixed.

**Comment by hoverbike1** [comment]
yeah sorry i didn't really notice until i got back home from the shops
should be all good now
