### ISSUE TITLE
mod make emulator crashes

### ISSUE THREAD

**Issue by armoiredu44** [HolographicWings/TOTK-Mods-collection#127]
Sweetmini 1008p - FXAA Off - Includes FSR and DynRes Disabler (1.1.0-1.1.1) makes the emulator crashes when i click on properties

**Comment by hoverbike1** [comment]
Thats just Yuzu. In these two months or so, I have never really used 1008p much outside verifying that it works - and this problem exists regardless of which mods I use. Even none at all.
