### ISSUE TITLE
Shadows1024 TOTK 1.0.0 @nsobid wrong

### ISSUE THREAD

**Issue by WardedPredator** [HolographicWings/TOTK-Mods-collection#128]
Looks like the code at the very top of the patch is incorrect for TOTK 1.0.0 and should be @nsobid-082CE09B06E33A123CB1E2770F5F9147709033DB

?

**Comment by HolographicWings** [comment]
fixed
https://github.com/HolographicWings/TOTK-Mods-collection/commit/3a7135e47239e215da5ab12c90e84b1510528b9c
thanks you for report
