### ISSUE TITLE
You told me to post on your github, then you delete what I wrote.

### ISSUE THREAD

**Issue by OldManKain** [HolographicWings/TOTK-Mods-collection#132]
Give theboy181 his credit, sweetmini aka M&M cannot make exefs mods.

**Comment by SpockBauru** [comment]
I have no idea who or what are you talking about, please give context next time. If there is missing the credit for some modder please open the config.yaml file for for the mod in question and point where is the mistake.

**Comment by HolographicWings** [comment]
> Give theboy181 his credit, sweetmini aka M&M cannot make exefs mods.

Accusing me to removed something
Read this https://github.com/HolographicWings/TOTK-Mods-collection/discussions/131
And answer please, explanations interest me

**Comment by HolographicWings** [comment]
> Give theboy181 his credit, sweetmini aka M&M cannot make exefs mods.

Accusing me to removed something
Read this https://github.com/HolographicWings/TOTK-Mods-collection/discussions/131
And answer, explanations interest me

**Comment by vasilvestre** [comment]
Continue in #131 but don't spam issues and discussions please.
