### ISSUE TITLE
Question: Compatibility with 1.2.0 version please?

### ISSUE THREAD

**Issue by VictorStepPersonal** [HolographicWings/TOTK-Mods-collection#133]
Thank you a lot for your mods collection!

**Comment by JonathanPitre** [comment]
I can't seem to be able to reach  60 fps no more so yeah I don't think the fps unlocker mods are 1.2.0 compatible yet

**Comment by JonathanPitre** [comment]
confirmed, look at the latest comments

https://www.reddit.com/user/ChucksFeedAndSeed/comments/14p6hq0/beta4_totk_dynamic_fps_v154beta4_config_toggles/

**Comment by SpockBauru** [comment]
There will be several mods compatible with 1.2.0 on the next release, but it will take a while. 
We will try to release next weekend but no promises!

**Comment by SpockBauru** [comment]
Mods Collection v2.3 released! Added about 100 mods compatible with TOTK 1.2.0, modders are really quick this time! Thanks you all!
