### ISSUE TITLE
Please split the archive. The size is nearly 500MB! (Save energy, money and time)

### ISSUE THREAD

**Issue by LtqxWYEG** [HolographicWings/TOTK-Mods-collection#135]
Hi

Please  create extra archives for Aspect Ratio mods and Lazy Packs.  
Reasoning: Aspect Ratio mods are rarely used and take up the most space. Steam hardware survey shows that ~80% have 16:9 monitors and using 16:9 ratio for 16:10 monitors is fine too. (Interestingly, almost 5% have monitors with a ratio of 683/384. I assume that's the Steam Deck.) And Lazy Packs take up more than 1/5 the space.

**This means that in 80% of the downloads 45.4% (208MB) is wasted traffic due to aspect ratio mods!** - (and potentially 22.7% (104MB) wasted due to lazy packs.  
Assuming there are a couple thousand times more downloads than people watching (44): That might be 88,000 * 312MB = 27.456 TB wasted traffic! (Reasoning: I am one of the few downloaders with a Github account and I don't see a reason for watching any repo.)

This will save energy, money and time.

Kind regards

**Comment by jaycc3000** [comment]
perhaps you could *.7zip it's 130 MB vs 457 MB ?

**Comment by LtqxWYEG** [comment]
Yes, but that's not entirely the point.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by vasilvestre** [comment]
Everything is 7zip in releases

This include more automation and with zip per versions, it's a bit too much releases files.

**Comment by hoverbike1** [comment]
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/8d454089-903f-4740-805b-5d73028baad7)

Just download the 7z archive.

**Comment by sk-lstein** [comment]
I know this is a closed issue, but just want to point out to the managers of @vasilvestre and me which are available to use, where you can pick what you need
