### ISSUE TITLE
Cheat Free Autobuild causes infinite autosave after the Homegrown in Hateno quest (maybe in other cases too)

### ISSUE THREAD

**Issue by LokoMaroko** [HolographicWings/TOTK-Mods-collection#137]
Just like in the title. 
After disabling the cheat everything is back to normal. Game version 1.2.0. 

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/26610622/aa088c1e-291f-4772-a4dc-b28579470137)

It's a pity, because it's the only cheat I use. It greatly improves the QoL of the game.

**Comment by SpockBauru** [comment]
The same happens with other versions of the game?

**Comment by hoverbike1** [comment]
Free Autobuild Alternate (1.0.0 to 1.2.0)
- "Tell him to try that instead" (From StevenssND

**Comment by StevensND** [comment]
> Just like in the title. After disabling the cheat everything is back to normal. Game version 1.2.0.
> 
> ![image](https://user-images.githubusercontent.com/26610622/253301407-aa088c1e-291f-4772-a4dc-b28579470137.png)
> 
> It's a pity, because it's the only cheat I use. It greatly improves the QoL of the game.

Could you share your save before complete the mission?. 

I've been trying another quests in Hateno and everything's working fine.

**Comment by LokoMaroko** [comment]
It's weird. Have you tried the mission I mentioned there is a problem? I played with this cheat for a few days and there was no problem, the only thing on this mission was that the game kept saving forever (it didn't hang, the music was playing and the fog was moving ... the saving sign was also moving). I have a game save before this mission - can share. It's slot 02. 

Here's link: https://pixeldrain.com/u/JUjC3Kup

**Comment by StevensND** [comment]
> It's weird. Have you tried the mission I mentioned there is a problem? I played with this cheat for a few days and there was no problem, the only thing on this mission was that the game kept saving forever (it didn't hang, the music was playing and the fog was moving ... the saving sign was also moving). I have a game save before this mission - can share. It's slot 02.
> 
> Here's link: https://pixeldrain.com/u/JUjC3Kup
> 
> Sorry, I accidentally closed the issue. I reopened. I'm a newbie when it comes to github xD

Ok. I can confirm that with the first Free Autobuild (No Alternate) this error happens + I'm stuck in infite saving. However if I use the [Alternate version](https://github.com/HolographicWings/TOTK-Mods-collection/tree/main/Mods/Cheats/Free%20Autobuild%20Alternate%20(1.0.0%20to%201.2.0)) everything is working fine.

**Comment by LokoMaroko** [comment]
> > It's weird. Have you tried the mission I mentioned there is a problem? I played with this cheat for a few days and there was no problem, the only thing on this mission was that the game kept saving forever (it didn't hang, the music was playing and the fog was moving ... the saving sign was also moving). I have a game save before this mission - can share. It's slot 02.
> > Here's link: https://pixeldrain.com/u/JUjC3Kup
> > Sorry, I accidentally closed the issue. I reopened. I'm a newbie when it comes to github xD
> 
> Ok. I can confirm that with the first Free Autobuild (No Alternate) this error happens + I'm stuck in infinite saving. However if I use the [Alternate version](https://github.com/HolographicWings/TOTK-Mods-collection/tree/main/Mods/Cheats/Free%20Autobuild%20Alternate%20(1.0.0%20to%201.2.0)) everything is working fine.
> 
> The cheat that you're probably using (**No Alternate**) to be used on Switch **needs to be activated while the game is being released**.
> 
> **The Alternate version fixes this so that it can be activated when you are already playing** ... that is, when you have 10-15 mins of gameplay and you want to activate it.
> 
> So ... I think the No Alternate version interprets that after finishing the mission the cheat needs to be reactivated creating the infinite loop and that's why the game freezes and doesn't work anymore until you restart it. However if you complete the mission again the same thing will happen again.
> 
> Yuzu/Ryujinx will have the same behaviour.

Yup, I'm playing on yuzu emulator on the latest version of EA. For now, because I just ordered a cheap Switch V1 console and I'm going to jaibreak and most of the mods I use on the emulator are going to the console :D


So you're saying that the alternative version will work? If so, I'll try and let you know.

Thanks for the confirmation and I hope I helped in some way :D

**Comment by StevensND** [comment]
> Yup, I'm playing on yuzu emulator on the latest version of EA. For now, because I just ordered a cheap Switch V1 console and I'm going to jaibreak and most of the mods I use on the emulator are going to the console :D
> 
> So you're saying that the alternative version will work? If so, I'll try and let you know.
> 
> Thanks for the confirmation and I hope I helped in some way :

Yes, the alternative version works. In fact I have already requested that they remove the other one because of this bug.

I wish I had a jailbroken Switch. It would make the job of making mods a lot easier.

**Comment by LokoMaroko** [comment]
Yes, it's working :D
