### ISSUE TITLE
Linux/ Steam Deck Lazy Pack Support

### ISSUE THREAD

**Issue by geowarin** [HolographicWings/TOTK-Mods-collection#140]
Hello!

The new Lazy Pack Generator is looking great.
It is however a less convenient solution for Linux and Steam Deck users, and I would argue, to all users in general.

Previously, I was just drag and dropping the appropriate lazypack in my mods folders and be done with it.

Is there any plan to re-upload the most common combinations (as before) in complement of the generator for more exotic setups?

**Comment by hoverbike1** [comment]
i'll take a look at it

**Comment by hoverbike1** [comment]
can you give this a whirl and tell me if its good?
i don't expect it to automatically find and fill in your yuzu directory, thats an entirely different file system to wade around in, so you'll have to put that in yourself

github is limited to 25mb attachments, so you can find it here:
https://pixeldrain.com/u/iR55PU3J

**Comment by hoverbike1** [comment]
new versions, please test them out
one file
https://pixeldrain.com/u/jddFwfUN
folder version
https://pixeldrain.com/u/d7bBxLpW

**Comment by geowarin** [comment]
Hey good work. I haven't tested it but I think a command line version of the tool would be useful.
That way we could create a github pipeline that auto generates the lazy packs.
What do you think?

**Comment by hoverbike1** [comment]
you're gonna have to use smaller words for dumb dumbs like me
i tried googling that stuff and all i got was a headache

**Comment by geowarin** [comment]
Lol sorry!
The lazy pack generator could have 2 "modes":

- The current one with a user interface (buttons and all)
- And another one that you call from cmd like so: "python lazypack.py -res 1920x1080 -fps 20 -black-screen-fix"

That's because it is easier to automate with the command line.

With a command line tool I could create a [github pipeline](https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/) that downloads the generator then execute it multiple times to generate the most useful combinations.
Then we can upload them as artifacts on a github repo (lazy lazypacks :smile:).

So people who have a steam deck (720p + 30fps + blackscreen) or a 1920p screen  (1920p + 60fps + blackscreen + xbox) would just download the zip and not have to use the generator themself.

**Comment by hoverbike1** [comment]
sorry for the late reply, i have been distracted and busy.
this seems like something worth looking into, but also something more appropriate for the original repository for lpg.

lets continue the discussion over here 👍 
https://github.com/hoverbike1/lazy-pack-generator
