### ISSUE TITLE
Update Aspect Ratio mods

### ISSUE THREAD

**Issue by Fruithapje21** [HolographicWings/TOTK-Mods-collection#142]
Pretty much all of the UI related problems that the previous version had are now fixed. The only problems remaining are that pre-rendered cutscenes play stretched and some camera related stuff. You can find the updated mods at [TOTK-Ultrawide/mods](https://github.com/Fruithapje21/TOTK-Ultrawide/tree/main/mods), or you can generate them using the tool.

**Comment by hoverbike1** [comment]
looking good!
im curious, the blackscreen-fix thats shipped with each aspect ratio, has it been modified?
it appears so, as the file size is significantly larger!

**Comment by Fruithapje21** [comment]
I will have a look later just to be sure, but I think it's just a matter of what compression level and dictionary are used.

**Comment by hoverbike1** [comment]
it'd very much like to know if we can remove them, as they cause incompatibility with controller UI mods.

**Comment by Fruithapje21** [comment]
Ah, I get what you mean now. No, blackscreenfix, aspect ratio mods, and controller mods all change the same file. Both the aspect ratio mods and controller mods come with blackscreenfix included solving that issue, but they are still incompatible with each other. Me and Fayaz have both created our own tools to merge the two. If you really want I can loop over all controller mods and merge the aspect ratio fixes. It would create a lot of files (you would need every combination of controller and aspect ratio), but this might be preferred over having to use some external tool. Let me know what you think.

**Comment by Fruithapje21** [comment]
Have you given this a thought yet? Also, sub-16:9 aspect ratios now support UI fixes too. I have pre-build versions of every aspect ratio found in this repo.

**Comment by hoverbike1** [comment]
> Have you given this a thought yet?
Yes, i discussed it with Spock, and we decided against it, it being Blackscreen-fix for each individual controller type, as it would require hundreds of controller mods.

>  sub-16:9 aspect ratios now support UI fixes too
I've noticed some new stuff on your repo, I hope to have those added for this sunday's release.

**Comment by hoverbike1** [comment]
alright, got everything copied over.
i was missing an update for steam deck / xbox ui, so if you want me to sneak those in, let me know.
will post them with next update - currently trying to get lazy pack generator working correctly on linux/steamdeck.

**Comment by Fruithapje21** [comment]
I decided that I want my utility to solely be a tool to patch game files to work with any aspect ratio. This way, it is flexible enough to be something that can be build upon for other projects, and will still be maintainable even after I decide to longer update it. I have therefore discontinued any aspect ratios mods with a controller mod included. It is of course still possible to create these combined patches using the tool (patch the controller mod instead of the default included blackscreenfix). It is kind of unfortunate we don't have automatic merging of mods yet. If you want to incorporate TOTK-Ultrawide into the lazy pack generator let me know.

Some other things:
It seems you have only updated the <16:9 aspect ratios. The >16:9 aspect ratios also received some small changes. You should be able to just drag replace the whole folder.
The last bullet point under Aspect ratio "UI rescaling only works for 16:10 and ultrawide (>16:9) aspect ratios" should be removed, and "Pre-rendered cutscenes play stretched" should be added.

**Comment by hoverbike1** [comment]
> It seems you have only updated the <16:9 aspect ratios.

I have double and triple checked - everything, except the Xbox / Steamdeck aspect ratio mods were updated.

> The last bullet point under Aspect ratio "UI rescaling only works for 16:10 and ultrawide (>16:9) aspect ratios" should be removed, and "Pre-rendered cutscenes play stretched" should be added.

Done, and done.

**Comment by Fruithapje21** [comment]
I just noticed that I've made a critical error in the >16:9 v1.0.0 exefs file. It accidentally uses the <16:9 format instead. New versions are up or you can only replace the affected files: https://github.com/Fruithapje21/TOTK-Ultrawide/commit/c02c042038df1bfacfe924bc20ad526b60f28efe

**Comment by hoverbike1** [comment]
there we go, the affected files were replaced with the new ones as per your request

thank you for taking the time to check if everything was OK!
