### ISSUE TITLE
Lazy pack dont find my yuzu folder

### ISSUE THREAD

**Issue by LordAnassCrous** [HolographicWings/TOTK-Mods-collection#146]
Hello,

I have a portal version of yuzu, and when i try to select the folder, it dosent work

My Yuzu is here (0 files in roaming)
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/140973093/345d8038-8961-484d-a65d-fcffbbd64cd5)

When i select the folder YUZU (even when i select the folder "Yuzu Early Access") it doesnt appear here
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/140973093/9abdcd00-d21e-4359-a64b-b9efe31e4264)

If you have any idea/solution, i will welcome it
Thank you

**Comment by hoverbike1** [comment]
Try selecting the "user" folder.
What operating system is this? Linux?

**Comment by LordAnassCrous** [comment]
> 

Even when im using it, it doesnt work

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/140973093/475790f0-e414-471e-b28b-95c2489c5031)

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/140973093/43b055f2-305c-4833-b39c-3779375cabc3)


(the message shows "sucess" but mods doesnt appears in yuzu and the file path isnt present as in the tutorial)


I'm using w11
r5 3600
16gb
rx 5600 xt

**Comment by LordAnassCrous** [comment]
nvm i refreshed and it looks working

now i just have a problem for lunching my game but there isnt relation with ur mods/lazy pack

thank u
