### ISSUE TITLE
Make the app open source 

### ISSUE THREAD

**Issue by hugo-sna** [HolographicWings/TOTK-Mods-collection#148]
Make 'Lazy Pack Generator' open because it is hard to trust a software like this

**Comment by SpockBauru** [comment]
Maybe you need some glasses: 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/67930504/466bf201-7bea-4077-aba7-0e0ca7dae82f)

**Comment by hugo-sna** [comment]
Ok, thanks but you could be nicer, we're on github not discord
