### ISSUE TITLE
Select what aspect ratio you want through the Lazy Pack generator

### ISSUE THREAD

**Issue by aflbos** [HolographicWings/TOTK-Mods-collection#149]
Just to make life a bit easier for the lazy ones (like myself lol) make it so that we can select which aspect ratio we want in the Lazy Pack generator, and also make it so that they are compatible with the UI mods. But if that is not possible then it's ok, you devs have already done a lot for the TOTK modding community anyway, so thank you :)

**Comment by Fruithapje21** [comment]
I think what Chuck means when he says he is working on aspect ratios is some resolution related patch to make the game less blurry when rendering in ultrawide. Right now the ultrawide mod just increases the fovx while using the same amount pixels, essentially leading to strechted out pixels. Dynamic fps still only supports 16:9 resolutions I believe. I don't think Chuck is working on changing the actual aspect ratio or on UI changes. Anyway, I'm just guessing. Probably should indeed just wait and ask him directly to be sure.

**Comment by hoverbike1** [comment]
say, has any of you had any luck contacting him?
i've been trying for over a month now, and he's just permanently unresponsive

**Comment by hoverbike1** [comment]
New TOTK Optimiser by @MaxLastBreath  features aspect ratio functionality
