### ISSUE TITLE
Use the Releases Function of GitHub

### ISSUE THREAD

**Issue by Krutonium** [HolographicWings/TOTK-Mods-collection#15]
Instead of filling your git repo with zips, create the zips and make releases instead. Makes them easier to find and keeps them out of source control; They shouldn't be in there in the first place. I can help if you'd like.

**Comment by HolographicWings** [comment]
> Instead of filling your git repo with zips, create the zips and make releases instead. Makes them easier to find and keeps them out of source control; They shouldn't be in there in the first place. I can help if you'd like.

I'm not sure to understand, the zips are in releases, i just place them in a folder from the repo too
https://github.com/HolographicWings/TOTK-Mods-collection/releases

**Comment by Krutonium** [comment]
Oh, for me it wasn't showing anything in there for me earlier. Fair enough! You still probably shouldn't have them in the repo itself though.
