### ISSUE TITLE
Followed the setup guide after updating to 1.2.0 and now I'm getting slowdowns

### ISSUE THREAD

**Issue by DinoNuggies7** [HolographicWings/TOTK-Mods-collection#151]
Before I updated I had fps drops and such, but I didn't have slowdowns. It's almost like the Dynamic FPS mod just isn't working, besides the 60fps one.

**Comment by hoverbike1** [comment]
are you using the most recent lazy pack generator?

**Comment by DinoNuggies7** [comment]
I tried that, yes. Same results

**Comment by hoverbike1** [comment]
does downgrading the game update to 1.1.2 resolve the issue for you?

**Comment by DinoNuggies7** [comment]
I would assume that would fix the problem, I was just playing it earlier, but it wouldn't resolve my issue.

**Comment by hoverbike1** [comment]
if game update 1.1.2 does not have the issue, then i'd recommend you stick to that until further updates.

**Comment by DinoNuggies7** [comment]
Any idea what could be causing issues though? I mean, I seem to be the only person with this issue, so it's gotta be something of my fault.

**Comment by hoverbike1** [comment]
possibly a bad dump.
bad shaders.
bad settings.

the only way to narrow down those possibilities is to start flicking switches.

**Comment by DinoNuggies7** [comment]
Odd, I never really had slowdowns until 1.2.0, but nevertheless they occur with and without DynamicFPS, so it's just hardware I suppose.
