### ISSUE TITLE
without mods in tears of the kingdom 1.2.1

### ISSUE THREAD

**Issue by asp0909** [HolographicWings/TOTK-Mods-collection#159]
Why are there no mods and cheats for tears of the kinddown 1.2.1??? Is there any problem with that update? I've searched and found almost nothing

**Comment by Charliviv97** [comment]
You just have to go to other "issues" and read the latest messages they have

**Comment by SpockBauru** [comment]
Duplicated of https://github.com/HolographicWings/TOTK-Mods-collection/issues/156
Closing
