### ISSUE TITLE
60fpsBlackscreenFix and CutsceneFix mod has released

### ISSUE THREAD

**Issue by k0t0ry** [HolographicWings/TOTK-Mods-collection#18]
https://www.reddit.com/r/NewYuzuPiracy/comments/13hq70a/60_fps_mod_black_screen_fix_not_thoroughly_tested/?utm_source=share&utm_medium=web2x&context=3

**Comment by k0t0ry** [comment]
60fps CutsceneFix mod has released in LOZ: Tears of the Kingdom 20fps, 30fps & 60fps Patch 0.3.7.2
https://gbatemp.net/download/loz-tears-of-the-kingdom-20fps-30fps-60fps-patch.37996/

**Comment by HolographicWings** [comment]
Hello, we added the cinematic fix from theboy181 but not released yet, about the blackfix fix i can't do anything i don't get over 35fps and my blackscreen issues are too rare to test the fixes, i ask to someone else from the repo to add the better blackscreen fix.
