### ISSUE TITLE
Using the 30fps mod + speed up as recommended breaks save times.

### ISSUE THREAD

**Issue by UdonOli** [HolographicWings/TOTK-Mods-collection#2]
The timestamp on saves breaks when using speed up. Recommending this without notifying users of this issue could cause panic.

**Comment by HolographicWings** [comment]
Thanks you, i'll try it myself and warn for issue on the front page

**Comment by HolographicWings** [comment]
Done, i wrote it on the front page

**Comment by hoverbike1** [comment]
Tested in Yuzu Stable 1435
Tested in Yuzu EA 3592

Problem appears solved in both distributions.

I think we should just make a caveat that all of this is only tested on Yuzu EA.
I certainly don't feel incentivised to do twice the testing haha.
Perhaps if someone wants to test stable for us, we can use their information.

**Comment by UdonOli** [comment]
I am using yuzu stable lmao - I'm not sure if i was using 1434 or not though so I might see if its been patched since yesterday

**Comment by UdonOli** [comment]
nah it still seems to occur - even with the 30fps + speed up?
perhaps this is a yuzu issue that's been fixed in EA

**Comment by UdonOli** [comment]
You can probably remove this warning.

**Comment by UdonOli** [comment]
Actually it definitely seems like a yuzu issue - I think that maybe it has to do with being focused on the application.
