### ISSUE TITLE
Duplicate LOD Patch

### ISSUE THREAD

**Issue by BleakBluets** [HolographicWings/TOTK-Mods-collection#20]
The patch "Graphics - LOD Patch - We are unsure about it's effect" is just a duplicate snippet from the patch "Graphics - Disable LODs decrease when low FPS"

**Comment by akeryuuth** [comment]
It does look to be the same (although I still don't know what it does)

**Comment by HolographicWings** [comment]
Hello, they are not same
you can see both codes here : 
https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/Mods/Graphics%20-%20LOD%20Patch%20-%20We%20are%20unsure%20about%20it's%20effect/exefs/1.1.0.pchtxt
https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/Mods/Graphics%20-%20Disable%20LODs%20decrease%20when%20low%20FPS/exefs/1.1.0.pchtxt
