### ISSUE TITLE
Small Key Shrine Bug

### ISSUE THREAD

**Issue by claudiocla87** [HolographicWings/TOTK-Mods-collection#25]
opening a chest containing a small key the game says you already have too many and won't let me continue to the shrine even using the reset cheat
![issue](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134015833/2a4053a3-0d17-454e-8fd9-104e7e09a952)

**Comment by HolographicWings** [comment]
What mods do you use ?

**Comment by claudiocla87** [comment]
Thanks for the quick response. I really appreciate your work!

Attached are screenshots of the mods I'm using

Can you help me?? I don't want to have to start over :(
![Immagine](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134015833/019014f0-1eff-45ae-b288-af93b0306c2b)

**Comment by HolographicWings** [comment]
Hmm, i never tested any cheat, i don't know the secondary effect they could have. I'm sorry but i don't know, maybe could you try without mods and say me if you still have the bug.
If remove the mods fix the bug, could you try any of them separately ? That will help us to document possible issues with mods.

**Comment by claudiocla87** [comment]
all tests have been performed

die

no update

single mod

no mod

other shrine

from yuzu to Ryujinx

surely one of the unlimited counters is +1 when you use the Small key

knowing the offset you could add in the mod cheat resets

I hope for a resolution :(

**Comment by hoverbike1** [comment]
What is the name of the shrine?
I'll go test it, perhaps it is amongst the things that patch 1.1.1 corrects.

**Comment by claudiocla87** [comment]
hi thanks for your interest

Saryotanog Shrine is where I see the problem

  the first shrine where i found the key was the one in the sky In-Isa Shrine

when a small key is taken you see a counter on the top left which becomes +1 and makes it visible to you when you use it the counter goes to 0 I think this is the problem

this is a video where you can see this counter and it is precisely the shrine where the problem occurs

![error](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134015833/ed85cfa3-96ec-45e0-a78e-c3db8a55f876)

https://www.youtube.com/watch?v=cyCmKuYdfqw

TIME 0:26


![error 2](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134015833/a867c059-e516-4612-ae74-a2406191c324)

the key in my game screen is missing


in the savegame editor i can't find anything that can give me reference to this key


:(

**Comment by hoverbike1** [comment]
I have tested shrine - works here.
Checked savegame editor - i can't find anything that can help there either.

Have you tried disabling all mods (except update) and then enabling the "reset cheats" while going ingame and playing?

**Comment by claudiocla87** [comment]
Thanks I managed to solve using cheat engine after a day of trying :D

**Comment by HolographicWings** [comment]
I close the issue
