### ISSUE TITLE
Request: Separate Cheats and Visual Mods

### ISSUE THREAD

**Issue by nicodemus144** [HolographicWings/TOTK-Mods-collection#29]
I'm only here for the visual mods and have no interest in cheats. Every package i have to sift through the cheats to remove them.

Can you just package them separately please?

Thanks!

**Comment by HolographicWings** [comment]
When you extract a ZIP you can only select the mods you want.
Theres is already too much things to manage.

An exemple : 
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/19623115/1dfef39e-8c4d-4e77-a4fd-461e687f410e)

**Comment by nicodemus144** [comment]
i know how that works. i'm saying, either way, it puts it on the user to remove/not select these items every single time you update, which is often.

as opposed to just not bundling them all together. but it's up to you.

**Comment by HolographicWings** [comment]
My bad, this topic is similar to #34 
We will think about, the risk is to get issues because someone dropped the whole Graphics folder in his yuzu mods folder and ask why that don't work.

**Comment by nicodemus144** [comment]
thank you! love the folder reorg in 1.6!

**Comment by HolographicWings** [comment]
you can thanks Socats for it

**Comment by HolographicWings** [comment]
It's now done, i close the issue
