### ISSUE TITLE
All combos with 60fps so far locked at 30fps

### ISSUE THREAD

**Issue by physixtential** [HolographicWings/TOTK-Mods-collection#30]
Sorry I'm sure I'm missing something and not sure where else to reach out. I've been successfully using a 60fps mod outside of your mod paks, but every version of 60fps you have provided, including the 1.4.4 update with 
<img width="315" alt="image" src="https://github.com/HolographicWings/TOTK-Mods-collection/assets/55558141/eea6ee99-2f66-4725-ac66-36dddf832f5a">
is just locked at 30fps for me. I have vsync off, and I know I can get 60 fps. Any clues as to why these just don't work vs others?

I am on zelda update 1.1.0 btw.

**Comment by hoverbike1** [comment]
5 instances of missing @stop values from 60 fps memory values being patched.
Thanks for pointing this out!
I have pushed a new version, available for download now:
https://github.com/HolographicWings/TOTK-Mods-collection/releases/tag/v.1.4.4

Please test and report back.

**Comment by Uranite** [comment]
> 5 instances of missing of @Stop from 60 fps memory values being patched. Thanks for pointing this out! I have pushed a new version, available for download now: [`v.1.4.4` (release)](https://github.com/HolographicWings/TOTK-Mods-collection/releases/tag/v.1.4.4)
> 
> Please test and report back.

For some reason this causes totk to crash on launch

**Comment by molnizzle** [comment]
> 

Same for me. Every 60fps mod in this repo causes crash on launch for me.

**Comment by physixtential** [comment]
I just diffed your combo vs the 60fps file I know works (I don't remember where I got it...)
<img width="1083" alt="image" src="https://github.com/HolographicWings/TOTK-Mods-collection/assets/55558141/125405c5-b8e6-4724-a2eb-cb09983cf214">

**Comment by Uranite** [comment]
Just add an empty line under the `@stop`, it fixes the crash

**Comment by HolographicWings** [comment]
I found several missing @enabled too, i fixed that, i'm definitely against combo mods.

**Comment by molnizzle** [comment]
@Uranite it works! Thanks

@HolographicWings I disagree tbh, the stuff included in this bundle is basically good for anyone playing TotK. I really like it just needs to work lol

**Comment by HolographicWings** [comment]
> @Uranite it works! Thanks
> 
> @HolographicWings I disagree tbh, the stuff included in this bundle is basically good for anyone playing TotK. I really like it just needs to work lol

it's exhausting to read their work to correct everything.
And we have to apply the new updates to every combo.
I'll don't remove them anyway.

**Comment by hoverbike1** [comment]
> Just add an empty line under the `@stop`, it fixes the crash

Thanks for pointing this out
fixed 👍

**Comment by HolographicWings** [comment]
> Sorry I'm sure I'm missing something and not sure where else to reach out. I've been successfully using a 60fps mod outside of your mod paks, but every version of 60fps you have provided, including the 1.4.4 update with <img alt="image" width="315" src="https://user-images.githubusercontent.com/55558141/239547088-eea6ee99-2f66-4725-ac66-36dddf832f5a.png"> is just locked at 30fps for me. I have vsync off, and I know I can get 60 fps. Any clues as to why these just don't work vs others?
> 
> I am on zelda update 1.1.0 btw.

everything is fixed
