### ISSUE TITLE
60FPS Potato crashes Yuzu on game start

### ISSUE THREAD

**Issue by molnizzle** [HolographicWings/TOTK-Mods-collection#31]
Using this version: 1.1.0 - Potato Patch - 60 FPS - 1080P 1X scaling

If I comment out the 60fps code, it launches fine. 100% reproducible on my end. Same situation with the UI compatible version.

**Comment by AM800Mats** [comment]
Same thing for a friend of mine, but only with the 720p 60fps potato patches.

Using the 30fps versions of the potato patch, but then adding in the 60fps code manually works fine.

[yuzu_log.txt](https://github.com/HolographicWings/TOTK-Mods-collection/files/11519087/yuzu_log.txt)

![image_2023-05-19_191857328](https://github.com/HolographicWings/TOTK-Mods-collection/assets/50455027/f572331d-a988-47da-9196-263f49bd0f7c)

**Comment by molnizzle** [comment]
Can probably merge this with [issue 30](https://github.com/HolographicWings/TOTK-Mods-collection/issues/30) which has people reporting the same problem with the 60fps mods.

**Comment by HolographicWings** [comment]
Potato patch is from Hover, i assign the issue to him.

**Comment by Uranite** [comment]
Just add an empty line under the `@stop`, it fixes the crash

**Comment by hoverbike1** [comment]
> Just add an empty line under the `@stop`, it fixes the crash

fixed five instances of missing linebreaks
thanks for pointing this out 👍
