### ISSUE TITLE
Does the 1080p mod only break ambient occlusion when scaling is above 1x?

### ISSUE THREAD

**Issue by Uranite** [HolographicWings/TOTK-Mods-collection#32]
Hi, I noticed that the 1080p code for the potato patch is the same as the 1080p code in the standalone "1.1.0 - Resolution - 1080p - break Ambient Occlusion but 5 more FPS" mod.
Does this mean that the Ambient occlusion is only broken if the scaling is above 1x? If so, then the folder should be renamed.

**Comment by Uranite** [comment]
It seems that AO is fine on ryujinx with the 1080p mod regardless of the scaling, but on yuzu, scaling above 1x will break AO.
Source:
https://www.reddit.com/r/NewYuzuPiracy/comments/13lr6oi/comment/jkrz1tn/

**Comment by HolographicWings** [comment]
> Hi, I noticed that the 1080p code for the potato patch is the same as the 1080p code in the standalone "1.1.0 - Resolution - 1080p - break Ambient Occlusion but 5 more FPS" mod. Does this mean that the Ambient occlusion is only broken if the scaling is above 1x? If so, then the folder should be renamed.

I think yes, and about "5 more fps" i'll remove that, it's true only for weak GPUs, thanks for this issue i'll made changes.
