### ISSUE TITLE
"Potato Patch" should be called something else

### ISSUE THREAD

**Issue by molnizzle** [HolographicWings/TOTK-Mods-collection#33]
When people see "potato" they think it's a patch that downgrades visuals to increase performance on lower end machines. These mods exist for many games with this naming scheme. That's really not what they're doing here though -- should be renamed to cut down on confusion.

Maybe "lazy patch" or something similar?

**Comment by HolographicWings** [comment]
I'm agreed, i said to hover to don't name it potate but he is stubborn xD

**Comment by ajhix36** [comment]
I also agree, potato is not a good description because to most people it means something other than what hoverbike mans.

**Comment by Bossman2O7** [comment]
Remember in Portal 2 when GlaDos becomes a literal potato to portray how downgraded she had become?

**Comment by hoverbike1** [comment]
Renamed Potato Patches to Lazy Pack.
You guys have no sense of humour...
