### ISSUE TITLE
Classic Green Hylian Tunic Request

### ISSUE THREAD

**Issue by Bossman2O7** [HolographicWings/TOTK-Mods-collection#35]
I've been using this mod so much for BOTW, the original red one seems so out of place now.  Can this be ported somehow?

https://gamebanana.com/mods/167728

**Comment by HolographicWings** [comment]
I'll ask permission to add it

**Comment by Krutonium** [comment]
That mod is for BOTW?

**Comment by Bossman2O7** [comment]
Yes... and on CEMU.  I didn't expect you to just be able to grab it and add
it to your bundle.  I was hoping you'd have some connection to be able to
have it ported.  I guess I never even looked on banana to see if one
already exists though...
