### ISSUE TITLE
No cheats work for 1.1.1

### ISSUE THREAD

**Issue by Rmurray2006** [HolographicWings/TOTK-Mods-collection#36]
Title, tested and all the cheats do not work past the update 1.1.0. possible for some updates?

**Comment by PiEzochem** [comment]
32:9 could do with an update to the 1.1.1 patch aswell , any news ?

**Comment by HolographicWings** [comment]
> Title, tested and all the cheats do not work past the update 1.1.0. possible for some updates?

We added a link on the front page : 
[1.1.1 Cheats](https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20for%20Yuzu)

**Comment by WilliamTael** [comment]
> > Title, tested and all the cheats do not work past the update 1.1.0. possible for some updates?
> 
> We added a link on the front page : [1.1.1 Cheats](https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20for%20Yuzu)

The cheat txt file won't show up on YUZU game's proprieties.

**Comment by HolographicWings** [comment]
follow the folder architecture we have in our cheats, the cheats need to be in a 'cheats' folder, itself in a folder with the name of the cheat

**Comment by WilliamTael** [comment]
> follow the folder architecture we have in our cheats, the cheats need to be in a 'cheats' folder, itself in a folder with the name of the cheat /xxxxxx/cheats/xxxxxx.txt

It worked! I've renamed each 1.1.0 txt file to "168DD518D925C7A3" and pasted each new code inside. 
Maybe the only thing I was doing wrong could be that I was creating the "cheats" folders without the "s" at the end. 
Thanks!

**Comment by WilliamTael** [comment]
> follow the folder architecture we have in our cheats, the cheats need to be in a 'cheats' folder, itself in a folder with the name of the cheat /xxxxxx/cheats/xxxxxx.txt

Sorry to bother you, but... Is there a way to reduce the land fog like the Cemu had a mod for BotW? 
Also, is there a way to increase the swimming speed even more? Maybe without increasing Link's swimming animation speed.

**Comment by HolographicWings** [comment]
> > follow the folder architecture we have in our cheats, the cheats need to be in a 'cheats' folder, itself in a folder with the name of the cheat /xxxxxx/cheats/xxxxxx.txt
> 
> Sorry to bother you, but... Is there a way to reduce the land fog like the Cemu had a mod for BotW? Also, is there a way to increase the swimming speed even more? Maybe without increasing Link's swimming animation speed.

I dunno, check the cheat github i linked on the documentation

**Comment by Dark-talon** [comment]
Support for cheats will now need to be handled at https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom
We didn't create the cheats, so best to inform the creator if you have problems.
