### ISSUE TITLE
32:9 for 1.1.1

### ISSUE THREAD

**Issue by PiEzochem** [HolographicWings/TOTK-Mods-collection#37]
32:9 21:9 etc could do with an update to the new patch ? any news ?

**Comment by HolographicWings** [comment]
> 32:9 21:9 etc could do with an update to the new patch ? any news ?

The creator updated them : 
https://gamebanana.com/mods/443462
I'll update them here too another time

**Comment by PiEzochem** [comment]
> > 32:9 21:9 etc could do with an update to the new patch ? any news ?
> 
> The creator updated them : https://gamebanana.com/mods/443462 I'll update them here too another time

Got it,thanks alot

**Comment by Dark-talon** [comment]
These have now all been updated to 1.1.1.
