### ISSUE TITLE
Resolution mod for 1.1.1

### ISSUE THREAD

**Issue by AlphaManiac9779** [HolographicWings/TOTK-Mods-collection#38]
Hello can u update the resolution mods for 1.1.1 
Also I was using the 720p mod x3 for 4K is that the best method or should I be using the 1008p mod (also time what sorry I'm new to this 😅)

**Comment by HolographicWings** [comment]
hello, all resolution mods with Alternate method in their name will work in any version
But 720 is made with a 1.1.0 asset
It could probably reverse some updates done by the 1.1.1
You should use the 1008p x2 instead

**Comment by AlphaManiac9779** [comment]
No I didn't try 720p on 1.1.1 , 2x on 1008p is working with no issues anything above 2x crashes yuzu I'm on a 3080 .
