### ISSUE TITLE
Disable Dynamic Resolution causes crash after loading save file (Steam Deck)

### ISSUE THREAD

**Issue by vgf89** [HolographicWings/TOTK-Mods-collection#39]
I'm on a steam deck (stable channel for OS and client), with TOTK 1.1.1 and 1.5.5 mods collection. Enabling the "Disable Dynamic resolution when low FPS" mod causes Yuzu to freeze then crash when the save file ~finishes loading but before it actually gets in game (the Zelda logo loading bar fills, then it completely freezes and yuzu closes a while later) I was mistaken, it freezes right after the loading screen opens.~ It varies, sometimes it crashes at the beginning of the loading screen, sometimes at the end right before the fade, and very rarely it reaches in game before freezing and crashing.

I've tried on mainline 1436, 1439, and EA 3499. Exact same crash behavior in all of them. It crashes even if the dynamic resolution disabler is the only enabled mod.

EDIT: corrected info about when precisely the freeze/crash happens.

**Comment by HolographicWings** [comment]
Hello, can you send me a log after the crash ?

**Comment by vgf89** [comment]
[yuzu_log.txt](https://github.com/HolographicWings/TOTK-Mods-collection/files/11523590/yuzu_log.txt)

**Comment by HolographicWings** [comment]
[6219.214119] Debug <Critical> core/hle/service/filesystem/fsp_srv.cpp:operator():899: Assertion Failed!

hmm, i don't understand this error

**Comment by vgf89** [comment]
Right? The error looks like it has nothing to do with what the mod should be changing. And yet the game loads in normally if I don't use th mod.

As I said, 1436, 1439, EA 3499, and now EA 3601 all freeze then crash on that line, right before the loading screen should fade away, if the mod is active. The game loads in fine if the mod is off. I've tried deleting and adding the mod again too, no change.

If I uncheck the update (so the game is on 1.0.0) but leave the mod checked, it gets past the initial Yuzu launching bar then crashes a few seconds later on the black screen, and it produces the exact same error as the crash that happens after loading a save in 1.1.1. If I disable the mod then 1.0.0 launches normally then I can load my save and get in game fine. I'll attach the log from the 1.0.0+mod run in a moment.

**Comment by vgf89** [comment]
Odd discovery: if I run a combo pack that includes the dynres disabler (1.1.1, 1.1.0 - Resolution - New 1008p -FXAA Off, FSR Off, DynRes Off -Zero AO Bugs) from the 1.6.1 mod collection it loads fine? Hmm...

**Comment by vgf89** [comment]
I'm finding that the exact point is crashes actually varies. Sometimes it crashes at the beginning of the loading screen, sometimes at the end, and rarely it crashes right after getting in-game. It also doesn't *always* produce a log (but when it does, it's that same fsp_srv 899 assertion failed every time).

I'm at a loss.

**Comment by HolographicWings** [comment]
Honestly i don't know, i haven't made the mod and i never used a Steam Deck
Only thing i can advice you is to don't use the "Disable Dynamic Resolution"
I added an adviced configuration on the documentation.

**Comment by Foul-Tarnished** [comment]
This mod makes everything blurrier anyway, when used with the 1080p mod.

**Comment by Mario-119** [comment]
Same issue on my Steam Deck, using the latest Yuzu EA (3602 at time of writing) and the TotK 1.1.1 update

**Comment by HolographicWings** [comment]
This mod is only usefull when you run under 30fps anyway

**Comment by vgf89** [comment]
Doesn't the mod disable dynamic resolution though? The game switches between normal and reduced resolution frequently, and no it doesn't *quite* hold a stable 30FPS so the quality dips while I'd rather have it drop to 25 (which it ends up doing anyways since the bottleneck is mostly CPU, not GPU, but the game can't tell the difference)

**Comment by Mario-119** [comment]
Ryujinx is only getting 15-20 FPS for me on my Deck, Yuzu is hanging anywhere from 25-35 FPS usually

**Comment by HolographicWings** [comment]
> Ryujinx is only getting 15-20 FPS for me on my Deck, Yuzu is hanging anywhere from 25-35 FPS usually

i think that deserve a mention to @Foul-Tarnished who love to tease people using yuzu :P

**Comment by Foul-Tarnished** [comment]
Steam Deck bad

**Comment by HolographicWings** [comment]
> Steam Deck bad
> 
> btw giga brain to have piracy links inside credits.txt for some mods lmfao

Yes i thanks you to warned me, i changed them

**Comment by reptarien** [comment]
This happens for me on the free 1441 build as well. Next to instant crash with the *latest* version of this mod enabled specifically; I tried it both alone with no other mods on and just the 1.1.1 update, and with other mods: same result, load in, see the world for a few seconds (at most), crash. I'm using a RTX 3060 and Ryzen 5 1600, I had been playing the game with earlier editions of the mod on 1.1.0 fine. There is something wrong with the mod itself.

**Comment by TheKingEngineRevUp** [comment]
I too am experiencing this issue

**Comment by Dark-talon** [comment]
newest yuzu builds should fix crashes, please test

**Comment by vgf89** [comment]
Still crashes on EA 3612 for me :-/

**Comment by Mario-119** [comment]
Yup, issue is persisting here as well (unless using a multi-pack)

**Comment by SpockBauru** [comment]
Disable Dynamic Resolution removed from the repository. It was causing too many issues.
