### ISSUE TITLE
Crash with a combination of recent mods

### ISSUE THREAD

**Issue by amunchkin** [HolographicWings/TOTK-Mods-collection#40]
I recently got a crash during gameplay using a combination of recent mods with Ryujinx 1.1.809. I was running around in the rain on the Great Plateau.

- TotK 1.1.0
- Ryujinx 1.1.809
- Mods are from latest pull from this repo as of this issue's creation date/time

![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/133830916/50d32527-c81e-4786-b001-f1ad9015f1ce)

Main log: 
[Ryujinx_1.1.809_2023-05-20_10-17-07.log](https://github.com/HolographicWings/TOTK-Mods-collection/files/11522772/Ryujinx_1.1.809_2023-05-20_10-17-07.log)

Crash error log (from console):
[ryujinx-1.1.809-crash-mods.log](https://github.com/HolographicWings/TOTK-Mods-collection/files/11522771/ryujinx-1.1.809-crash-mods.log)

**Comment by HolographicWings** [comment]
FSR Sharpening is known to crash Ryuginx, it's why i ask to read the documentation, plus this mod alone is useless
Try to disable 1024x shadow too

**Comment by andymerskin** [comment]
Ahh I see, sorry for not reading it more closely. I was scanning the docs for notes and changes but I somehow missed that point. Thanks for pointing out 👍

I'm still using `totk-friends` v2 which has some FSR fixes baked in. That's been much smoother so far, and it includes 1080p / LOD fixes as well.

**Comment by amunchkin** [comment]
Ahh I see, sorry for not reading it more closely. I was scanning the docs for notes and changes but I somehow missed that point. Thanks for pointing out 👍

I'm still using `totk-friends` v2 which has some FSR fixes baked in. That's been much smoother so far, and it includes 1080p / LOD fixes as well.
