### ISSUE TITLE
Disable internal FXAA mod makes map cave icons not show up for newly discovered caves 

### ISSUE THREAD

**Issue by Epistolar1** [HolographicWings/TOTK-Mods-collection#41]
Mod list:
![Sem título](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134157219/d1754b3c-5f69-4714-815b-64e22c9ccc03)
The map cave icons are not showing up whenever I discover a new cave. After some troubleshooting, i found that the internal FXAA disable mod is the culprit. Without it the icons show up. With only it the map icons don't. Game ver 1.1.0 
mods from the 1.5.4 release save for the LOD mod, which's from the 1.5.5 release

**Comment by HolographicWings** [comment]
thanks you for report, while you have too much mods i can't add it as a known bug
i'm not supposed to support piracy, the file of your rom is clearly a crack
anyway FSR sharpener disabler is useless alone

**Comment by Epistolar1** [comment]
yeah using by itself does make the icons not show up

**Comment by Epistolar1** [comment]
yeah using it by itself makes the icons not show up
I understand the stance on piracy. I do own the game however i'm not really confortable doing all the shit to get it on pc, and i hate how it runs on og hardware
the FSR thing I don't get, i have both the sarpener and downscaling disabler, am i missing another fsr mod cause i don't see it on the zips

**Comment by ajhix36** [comment]
Are you using yuzu or ryujinx!

**Comment by Epistolar1** [comment]
yuzu

**Comment by shadowzach7** [comment]
Let me add this is also the case for me on Yuzu, tried with no mods and it works fine, tried with the Disable Internal FXAA mod on and new locations are no longer discovered and they do not show up on the map/minimap. This is quite annoying and borderline make it unusable unless you have already discovered all the locations. This happens to all new locations too, not just caves.

**Comment by chrisburgan** [comment]
I can also confirm that my map was not updating until Disable internal FXAA was removed. I have tested with only this mod enabled and the problem persists until I disable the mod again.

Game version 1.1.1
Yuzu 3599

**Comment by ajhix36** [comment]
Thank you for the reports, I've updated the FXAA mod to a new version. My testers found no issues with it anymore. Please open a  new issue if you do find another bug. Thank you!

**Comment by Serfrost** [comment]
@Dark-talon Can I ask which method you used to resolve this? I cannot replicate the problem but I've been getting the same reports with one of my mod releases.
