### ISSUE TITLE
Does `Resolution - 1026p - FSR Off, DynRes Off, FXAA Off` conflict with `Disable Internal FSR sharpening shader`?

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [HolographicWings/TOTK-Mods-collection#43]
It looks like `Resolution - 1026p - FSR Off, DynRes Off, FXAA Off` is a combination that includes `Disable Internal FSR sharpening shader`

**Comment by ajhix36** [comment]
Yes FSR is disabled, no sharpening shader mod is need.
