### ISSUE TITLE
Is this supposed to also work on switch ?

### ISSUE THREAD

**Issue by edricus** [HolographicWings/TOTK-Mods-collection#45]
I've been wondering if I can use mods to disable dynamic resolution and try 1008p with some overclocking but so far when trying those I get
```
A fatal error occurred when running Atmosphère.
Program ID: 010041544d530000
Error Desc: Data Abort (0x101)
```
Is this supposed to happen or I can run this on a switch and just doing it wrong ?

**Comment by Krutonium** [comment]
As far as I am aware, in theory they should work on Switch, but in practice, nobody is testing them on Switch.

**Comment by HolographicWings** [comment]
I haven't tested any of theses mods on switch sorry

**Comment by Dark-talon** [comment]
> I've been wondering if I can use mods to disable dynamic resolution and try 1008p with some overclocking but so far when trying those I get
> 
> ```
> A fatal error occurred when running Atmosphère.
> Program ID: 010041544d530000
> Error Desc: Data Abort (0x101)
> ```
> 
> Is this supposed to happen or I can run this on a switch and just doing it wrong ?

While I havent tested it on switch, you maybe will have more success with the new 1008p mod on real hardware
