### ISSUE TITLE
Longer days mod/cheat?

### ISSUE THREAD

**Issue by declandaman** [HolographicWings/TOTK-Mods-collection#47]
Wondering how possible it is to make mods/cheats for the day duration? I think default is way too quick. I've had a look through the dump files to see if it was moddable but no luck.

**Comment by HolographicWings** [comment]
I don't know sorry, did you searched on gamebanana ?

**Comment by FrostedMint** [comment]
I wrote an IPSwitch patch to do this on 1.1.0. I haven’t encountered any negative side-effects, but I have no idea what I’m doing, so use at your own risk, no warranty, etc.

Place in `timeofdaymod/exefs/1.1.0.pchtxt`:

```
@nsobid-D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3

@flag print_values
@flag offset_shift 0x100

@enabled
00af4b64 3cc46314
023e5c54 390000d0
023e5c58 205f4cbd
023e5c5c a6000014
023e5ef4 0819201e
023e5ef8 0129211e
023e5efc 56170014
023ebc54 79a10090
023ebc58 c4239c17
023ebc5c 00000041
@stop
```

The last byte is a little-endian IEEE754 floating point number that respresents a multiplier for how much slower the in-game clock progresses. The above version (`0x00000041`) is equal to 8.0, so each day lasts 8× longer, or 3h 12m total (96 minute days, 96 minute nights).

Other possible values (I haven’t test any of these):
- `0x0000003e` 8× faster (3 minute day/night cycle)
- `0x0000803e` 4× faster (6 minute day/night cycle)
- `0x0000003f` 2× faster (12 minute day/night cycle)
- `0x0000c03f` 1.5× slower (36 minute day/night cycle)
- `0x00000040` 2× slower (48 minute day/night cycle)
- `0x00002040` 2.5× slower (60 minute day/night cycle)
- `0x00004040` 3× slower (72 minute day/night cycle)
- `0x00008040` 4× slower (96 minute day/night cycle)
- `0x0000a040` 5× slower (2 hour day/night cycle)
- `0x0000c040` 6× slower (2h 24m day/night cycle)
- `0x0000e040` 7× slower (2h 48m minute day/night cycle)
- `0x00000041` 8× slower (3h 12m minute day/night cycle)
- `0x00001041` 9× slower (3h 36m minute day/night cycle)
- `0x00002041` 10× slower (4 hour day/night cycle)
- `0x0000f041` 30× slower (half “realtime”, 12 hour day/night cycle)
- `0x00007042` 60× slower (“realtime”, 24 hour day/night cycle)

I make no copyright claim whatsoever over any of this. Do whatever you want, repost to gamebanana, make it better, etc:

```
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
```

**Comment by declandaman** [comment]
Have been testing it for a bit, no issues so far! Thanks so much dude, and for the guide. I'll upload it to Gamebanana and credit you if that's cool?

**Comment by FrostedMint** [comment]
Glad it’s working for you! I’ll try to update it for 1.1.2 soon, got a lot on my plate at the moment but hopefully sometime in the next week?

> I'll upload it to Gamebanana and credit you if that's cool?

Cool with me! There’s an open request [here](https://gamebanana.com/requests/49137), feel free to claim the bounty or whatever, I don’t have a gamebanana account.

**Comment by HolographicWings** [comment]
> I wrote an IPSwitch patch to do this on 1.1.0. I haven’t encountered any negative side-effects, but I have no idea what I’m doing, so use at your own risk, no warranty, etc.
> 
> Place in `timeofdaymod/exefs/1.1.0.pchtxt`:
> 
> ```
> @nsobid-D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3
> 
> @flag print_values
> @flag offset_shift 0x100
> 
> @enabled
> 00af4b64 3cc46314
> 023e5c54 390000d0
> 023e5c58 205f4cbd
> 023e5c5c a6000014
> 023e5ef4 0819201e
> 023e5ef8 0129211e
> 023e5efc 56170014
> 023ebc54 79a10090
> 023ebc58 c4239c17
> 023ebc5c 00000041
> @stop
> ```
> 
> The last byte is a little-endian IEEE754 floating point number that represents a multiplier for how much slower the in-game clock progresses. The above version (`0x00000041`) is equal to 8.0, so each day lasts 8× longer, or 3h 12m total (96 minute days, 96 minute nights).
> 
> Other possible values (I haven’t test any of these):
> 
> * `0x0000003e` 8× faster (3 minute day/night cycle)
> * `0x0000803e` 4× faster (6 minute day/night cycle)
> * `0x0000003f` 2× faster (12 minute day/night cycle)
> * `0x0000c03f` 1.5× slower (36 minute day/night cycle)
> * `0x00000040` 2× slower (48 minute day/night cycle)
> * `0x00002040` 2.5× slower (60 minute day/night cycle)
> * `0x00004040` 3× slower (72 minute day/night cycle)
> * `0x00008040` 4× slower (96 minute day/night cycle)
> * `0x0000a040` 5× slower (2 hour day/night cycle)
> * `0x0000c040` 6× slower (2h 24m day/night cycle)
> * `0x0000e040` 7× slower (2h 48m minute day/night cycle)
> * `0x00000041` 8× slower (3h 12m minute day/night cycle)
> * `0x00001041` 9× slower (3h 36m minute day/night cycle)
> * `0x00002041` 10× slower (4 hour day/night cycle)
> * `0x0000f041` 30× slower (half “realtime”, 12 hour day/night cycle)
> * `0x00007042` 60× slower (“realtime”, 24 hour day/night cycle)
> 
> I make no copyright claim whatsoever over any of this. Do whatever you want, repost to gamebanana, make it better, etc. Any part of this that may be subject to copyright is hereby released into the public domain:
> 
> ```
> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <https://unlicense.org>
> ```

Awesome, we'll add it to the cheat section, except if you want to join the collaborators and do it yourself.

**Comment by FrostedMint** [comment]
Some people on gamebanana were having issues with it. The 3h 12m version works for me on Yuzu and Ryujinx, game version 1.1.0. I don’t know if there’s something better than IPSwitch patches for this, if there is I can look into updating it.

Someone there also suggested it might not work with some FPS mods because they modify some timing code? I’ve only tested it with FPS++.

**Comment by declandaman** [comment]
Yeah I've only used FPS++ too. I think it's a version thing, some people running 1.1.0 and 1.1.1 etc

**Comment by declandaman** [comment]
Let me know when you get around to the 1.1.1 and 1.1.1 versions and I'll chuck them on GB. No rush man, cheers!

**Comment by HolographicWings** [comment]
I added them, reopen the issue if you find the 1.0.0, 1.1.1 or 1.1.2 adresses.

**Comment by FrostedMint** [comment]
Update for 1.1.2; I don’t have a copy of 1.1.1.

```
@nsobid-9A10ED9435C06733DA597D8094D9000AB5D3EE60

@flag print_values
@flag offset_shift 0x100

@enabled
00ae3150 99810014
00b037b4 590100f0
00b037b8 20df40bd
00b037bc 46110014
00b07cd4 0819201e
00b07cd8 0129211e
00b07cdc fe980014
00b2e0d4 196701b0
00b2e0d8 1fd4fe17
00b2e0dc 00000041
@stop
```

Possible time multipliers are the same as above; replace `00000041` with desired value.

Annotated version:

```
7100ae314c __ __ __ __     // Existing code of patched function
// Go to first code cave
7100ae3150 99 81 00 14     b          codeCaveA
    shimReturn:
7100ae3154 __ __ __ __     // Existing code of patched function

    codeCaveA:
// Our custom time multiplier is stored at 0x7100b2e0dc; overwrite x25 with the
// page address for our custom time multiplier
7100b037b4 59 01 00 f0     adrp       x25,0x7100b2e000
// Use page address at x25 to load the our custom time multiplier into s0
7100b037b8 20 df 40 bd     ldr        s0,[x25, #0xdc]
// Go to second code cave
7100b037bc 46 11 00 14     b          codeCaveB

    codeCaveB:
// Divide current time "slice" (s8) by time multiplier (s0)
7100b07cd4 08 19 20 1e     fdiv       s8,s8,s0
// Add time slice (s8) to current time of day (s1)
7100b07cd8 01 29 21 1e     fadd       s1,s8,s1
// Go to third code cave
7100b07cdc fe 98 00 14     b          codeCaveC

    codeCaveC:
// Restore original value of x25 so the patched function can use it
7100b2e0d4 19 67 01 b0     adrp       x25,0x710380f000
// Return to patched function
7100b2e0d8 1f d4 fe 17     b          shimReturn
// Custom time multiplier value stored here
7100b2e0dc 00 00 00 41
```

**Comment by HolographicWings** [comment]
Added to last release.
