### ISSUE TITLE
FPS++ 60 fps issue

### ISSUE THREAD

**Issue by javsp** [HolographicWings/TOTK-Mods-collection#49]
When I enable the FPS++ 60 fps mod the game runs too fast when I move through the tabs in menus. Instead of that I prefer using 60 fps v4 + cutscene fix + DynamicFPS 1.42 (which don't have this bug). The problem is the combo mod that includes these 3 mods is not compatible with the last update 1.1.1 (or at least the name says that). Can you make this combo mod (60 fps v4 + cutscene fix + DynamicFPS 1.42) compatible with the update 1.1.1? 

Thanks, I really appreciate the job you're doing.

**Comment by HolographicWings** [comment]
i'll update it tomorrow, you can't use them separately ?

**Comment by HolographicWings** [comment]
> When I enable the FPS++ 60 fps mod the game runs too fast when I move through the tabs in menus. Instead of that I prefer using 60 fps v4 + cutscene fix + DynamicFPS 1.42 (which don't have this bug). The problem is the combo mod that includes these 3 mods is not compatible with the last update 1.1.1 (or at least the name says that). Can you make this combo mod (60 fps v4 + cutscene fix + DynamicFPS 1.42) compatible with the update 1.1.1?
> 
> Thanks, I really appreciate the job you're doing.

i'll update it tomorrow if i think about, you can't use them separately ?

**Comment by javsp** [comment]
Yeah, that’s what I’m using right now.

**Comment by javsp** [comment]
In addition to what I've said before 60 fps v4 + cutscene fix + DynamicFPS 1.42 make the game run at 60 fps in cutscenes so is not a perfect solution neither. I think I'll be using FPS++ 30 fps as long as these bugs are not fixed.

**Comment by HolographicWings** [comment]
> In addition to what I've said before 60 fps v4 + cutscene fix + DynamicFPS 1.42 make the game run at 60 fps in cutscenes so is not a perfect solution neither. I think I'll be using FPS++ 30 fps as long as these bugs are not fixed.

Use FPS++ 30fps and press ctrl + U to disable the framerate cap
Enable it back when you get a cinematic, it's the old method and you sure to don't have unespected issues

**Comment by javsp** [comment]
> > In addition to what I've said before 60 fps v4 + cutscene fix + DynamicFPS 1.42 make the game run at 60 fps in cutscenes so is not a perfect solution neither. I think I'll be using FPS++ 30 fps as long as these bugs are not fixed.
> 
> Use FPS++ 30fps and press ctrl + U to disable the framerate cap Enable it back when you get a cinematic, it's the old method and you sure to don't have unespected issues

If I do that (and I press 0Ctrl+U to unlock the frames) I get the same effect than using FPS++ 60fps: I'm moving through the tabs in the menu too fast, I mean I press L1 once but I move through the tabs 2 or 3 times. I remember this issue in BOTW as well when you played it at 60fps in Cemu (at least at the beginning, maybe it's fixed now).

Currently, the only way to avoid this is weird behavior is playing the game locked at 30 fps.

**Comment by javsp** [comment]
I can confirm that this 3 mods: 60fps Static + Cutscene fix + DynamycFPS 1.42 included in the last TOTK mod collection (1.6.5) work fine now: cutscenes play at 30 fps automatically and the speed moving through the tabs in menus is finally solved now.
