### ISSUE TITLE
Suggestion - add unbreakable hero equipments mod

### ISSUE THREAD

**Issue by Faruolo2** [HolographicWings/TOTK-Mods-collection#51]
Hello just a suggestion of mod that i think works in harmony with zelda totk. Since hero equipments are not overpowered  (hero sword only do 17 damage as a example) its nice to have it unbreakable to progress along with other weapons u can fuse for special ocasions.

i ve been using this mod: https://gamebanana.com/mods/443947

can u add it to the pack?

**Comment by HolographicWings** [comment]
> Hello just a suggestion of mod that i think works in harmony with zelda totk. Since hero equipments are not overpowered (hero sword only do 17 damage as a example) its nice to have it unbreakable to progress along with other weapons u can fuse for special ocasions.
> 
> i ve been using this mod: https://gamebanana.com/mods/443947
> 
> can u add it to the pack?

I could add it with the permission of the creator.
https://gamebanana.com/mods/license/443947
You could DM him if you want, with a screenshot of message where he accept his mod is redistributed, i'll add it.

**Comment by InfiniteParallel** [comment]
> Due to the nature of this MOD, it will conflict with a huge chunk of MODs later on, since it modifies every weapon in the game, the option already included in this pack is vastly superior since it won't cause conflicts.
> 
> And by that I mean we already have a cheat file that makes your weapons unbreakable.

For 1.1.1 I found that cheat no longer works. I need to test it with 1.1.2 once a few more graphics mods are updated to 1.1.2.

The mod in question is indeed problematic. I've had it cause several strange bugs.

**Comment by InfiniteParallel** [comment]
> @InfiniteParallel It does work, no offense but you simply have reading problems, there even a direct link for the updated Cheats.
> 
> ![image](https://user-images.githubusercontent.com/15495525/241849945-ef7c829c-8905-4241-9dbb-19ff1c000dfa.png)
> 
> Also included in the files in clear text, right on top of the Cheats folder,
> 
> ![image](https://user-images.githubusercontent.com/15495525/241850277-4fbb6705-c7b3-478f-b2f5-580afba1d2a8.png)

Yeah, no offense, then you are intentionally offensive. Shut up.

**Comment by InfiniteParallel** [comment]
As you can see from the link below, someone other than myself is also having the exact same issue:

https://gamebanana.com/posts/10790456
