### ISSUE TITLE
graphical errors (artifacts) in caverns

### ISSUE THREAD

**Issue by Menma-Uzum** [HolographicWings/TOTK-Mods-collection#53]
is there a mod to fix black triangles on rocks in caverns?  No graphic settings help.  (steam deck)

**Comment by Menma-Uzum** [comment]
![IMG_20230522_230436](https://github.com/HolographicWings/TOTK-Mods-collection/assets/101217173/77df961e-3773-4e5e-a07c-ae9e0eee2562)
![IMG_20230522_230446](https://github.com/HolographicWings/TOTK-Mods-collection/assets/101217173/0f4eb872-f557-4715-b251-759287d9feb8)

**Comment by HolographicWings** [comment]
Hello, never saw that bug yet, i dunno i'm sorry

**Comment by hoverbike1** [comment]
try adjusting the ASTC recompression settings in advanced graphics
start from uncompressed, and move to Bc3, and if that doesnt help, try BC1.
