### ISSUE TITLE
mod break laser in shrine

### ISSUE THREAD

**Issue by Farisoft** [HolographicWings/TOTK-Mods-collection#54]
when using the mod : 
1.1.1, 1.1.0 - Resolution - 1026p - FSR Off, DynRes Off, FXAA On - Minor bug, causing AO to flicker inside other shadows
lasers are invisible in shrines

**Comment by HolographicWings** [comment]
1026p break a lot of things, you should use 1008p, i think i'll remove it.

**Comment by 89pleasure** [comment]
I think it can cause issues for some users, not for all. So very system related, right?
Do you think it's best to delete a mod that just don't work for some but for others? Or is it just me who has not much issues with that mod?

**Comment by HolographicWings** [comment]
I think we should remove the 1026p they are buggy as fuck for almost everyone

**Comment by Dark-talon** [comment]
This isn't caused by a mod, invisible lasers happens when shaders compile async, and you have to leave and come back to fix.
