### ISSUE TITLE
20fps Static and 60fps Static 1.1.1 are same files

### ISSUE THREAD

**Issue by lfsgame** [HolographicWings/TOTK-Mods-collection#55]
They are actually 20 fps mod

**Comment by baconsplit** [comment]
File is still wrong unfortunately.
There are two extra lines at the bottom in your 60fps file compared to the original file

**Comment by HolographicWings** [comment]
Ye, i finally fixed it in the 1.6.5, failed in the 1.6.4 sorry
It is good now ?

**Comment by baconsplit** [comment]
Yes the file is correct now! Thanks for keeping this collecting up to speed.
Godsent for the current totk situation :)

**Comment by HolographicWings** [comment]
yw, i'm closing this issue now
