### ISSUE TITLE
Compressed file fails to download 

### ISSUE THREAD

**Issue by sjmendoza59** [HolographicWings/TOTK-Mods-collection#66]
The 7zip compressed file gives a virus warning and fails to finish downloading. Not sure why as the larger zip file works fine and I know it's clean. I think windows can't scan it and decides it's a threat and quarantines it. Something to look in to.

**Comment by vasilvestre** [comment]
> The 7zip compressed file gives a virus warning and fails to finish downloading. Not sure why as the larger zip file works fine and I know it's clean. I think windows can't scan it and decides it's a threat and quarantines it. Something to look in to.

It works ok to me. Can you share your Windows version and navigator ? Do you have an antivirus different than Windows Defender ?

**Comment by HolographicWings** [comment]
> The 7zip compressed file gives a virus warning and fails to finish downloading. Not sure why as the larger zip file works fine and I know it's clean. I think windows can't scan it and decides it's a threat and quarantines it. Something to look in to.

Windows can't natively scan a 7z file, it's why.

**Comment by Krutonium** [comment]
> > The 7zip compressed file gives a virus warning and fails to finish downloading. Not sure why as the larger zip file works fine and I know it's clean. I think windows can't scan it and decides it's a threat and quarantines it. Something to look in to.
> 
> Windows can't natively open/scan a 7z file, it's why.

Vaguely off topic, but handy to know for the future, Windows is getting native 7z/rar/most archive type supports in the near future.

**Comment by HolographicWings** [comment]
Windows needed 24 years to add 7zip support 👏
