### ISSUE TITLE
Add this fix for sky island lod plz

### ISSUE THREAD

**Issue by PhyX-Meow** [HolographicWings/TOTK-Mods-collection#75]
https://www.reddit.com/r/NewYuzuPiracy/comments/13uath8/totk_sky_island_lod_improvement_mods_v111_test/

Looks great.

**Comment by HolographicWings** [comment]
Already added ^^

**Comment by PhyX-Meow** [comment]
Sorry that I didn't recognize them. You are doing really good man!
