### ISSUE TITLE
New Feature: Script to enable/disable mods

### ISSUE THREAD

**Issue by Anatharias** [HolographicWings/TOTK-Mods-collection#79]
Hey, pretty nice collection of mods you have here. 
Though some of them are not compatible with each other !
It would be awesome if you would write up a little script that would rename the mods based on their compatibility with others.

if you'd want mod A, the script would rename mods C, D and E as [Incompatible] C, [Incompatible] D and [Incompatible] E
and if you'd disable A, and enable B, it would rename the others mods accordingly.
Why rename, maybe because it sounds the easiest ?
idk, but this would be a nice feature.

**Comment by HolographicWings** [comment]
well, hard to imagine how that would be possible without making N zips, N being the amount of mods
several people work on a mod manager, that will be our salvation
