### ISSUE TITLE
16:10 mod doesn’t work on steam deck. 

### ISSUE THREAD

**Issue by hanso-san** [HolographicWings/TOTK-Mods-collection#8]
No change to aspect ration when mod is applied. Attempting to force 16:10 in yuzu settings with mod applied only results in stretched 16:9.

**Comment by HolographicWings** [comment]
the HUD is known to be stretched, but the scene render is not
https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/README.md?plain=1#L46

**Comment by HolographicWings** [comment]
I close the issue, check regularly the gamebana page of the mod to see if the creator Fixed the issue
