### ISSUE TITLE
Conflicting information in README.md

### ISSUE THREAD

**Issue by Maleriandro** [HolographicWings/TOTK-Mods-collection#84]
In the README, for the **Disable Internal FSR Downscaling** mod, at the end says:
`It's recommended to use this mod with "Graphics - Disable Internal FSR Sharpening Shader" if you are on Yuzu.`

But then, in the **Graphics - Disable Internal FSR Sharpening Shader** mod, it says:
`Don't use this mod without "Graphics - Disable Internal FSR Downscaling".`
`It's recommended to use this mod with "Graphics - Disable Internal FSR Sharpening Shader" if you are on Yuzu.`

The second sentence of **Disable Internal FSR Sharpening Shader** nakes no sense. And the first one conflicts directly with the instructions on the **Disable Internal FSR Downscaling**.

**Comment by Dark-talon** [comment]
Thank you, the lines have been updated to say

Graphics - Disable Internal FSR Downscaling : This mod disables the game's FSR, Yuzu has its own FSR in the "Window Adapting Filter" in Graphics settings.
FSR is an optimisation method that reduces the game's internal resolution, and then upscales it using an algorithm (similar to DLSS but without advanced AI or temporal information).
FSR increases GPU performance, at the cost of some details and potential graphical artifacts on small geometry like leaves or grass.
It's recommended to use this mod with "Graphics - Disable Internal FSR Sharpening Shader" if you are on Yuzu.

Graphics - Disable Internal FSR Sharpening Shader : This mod disables the sharpening effect of post processed FSR Downscaling internally.
GPU Performance cost is already extremely low so disabling it will not improve it. It's recommended to use this mod with "Graphics - Disable Internal FSR Downscaling" if you are on Yuzu. BEWARE ! It seems that this mod could be responsible for crashes on Ryujinx.
