### ISSUE TITLE
stuck at launching screen

### ISSUE THREAD

**Issue by RandomGuy198** [HolographicWings/TOTK-Mods-collection#90]
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/134940416/63e10875-9ed7-4f53-9b4f-8722e9a128f9)
im stuck at this screen after load shader
Using dynamic fps +++, game version 1.1.0
plz help

**Comment by hoverbike1** [comment]
appears the shaders have to be rebuilt, so booting took a lot longer than usual
however, given enough patience, it did eventually load.
tested on ea 3625 - game version 1.1.0 - using 60 fps 1080p x1 UI compatible lazy pack

i'd suggest you check your settings, and be patient. if everything is done correctly, it _should_ work.
![image](https://github.com/HolographicWings/TOTK-Mods-collection/assets/57139770/af98d7ec-bb64-4711-b339-be0fb7fc3d2d)

**Comment by RandomGuy198** [comment]
> appears the shaders have to be rebuilt, so booting took a lot longer than usual however, given enough patience, it did eventually load. tested on ea 3625 - game version 1.1.0 - using 60 fps 1080p x1 UI compatible lazy pack
> 
> i'd suggest you check your settings, and be patient. if everything is done correctly, it _should_ work. ![image](https://user-images.githubusercontent.com/57139770/242244392-af98d7ec-bb64-4711-b339-be0fb7fc3d2d.png)

oh, it really work, but need more time to rebuild shader, thanks
