### ISSUE TITLE
a

### ISSUE THREAD

**Issue by Nvim** [HolographicWings/TOTK-Mods-collection#95]
- CPU :  i5-9600KF
- GPU : AMD RX 6700
- RAM : 16GB DDR4 2666Mhz
- Emulator : Yuzu
- Approximative Playtime :  
  - Yuzu : 50-70 hours
  - Ryuginx : -
- Average framerate : 
  - Yuzu : 45-60 in wilds (with dips), 25-40 in towns
  - Ryuginx : -
- API : Vulkan
- Notes : Using Arch Linux with zen kernel and gamemode, really smooth experience so far with Yuzu EA-3625 and recommended mods and settings from 1.8.5 release. I play in 2x render resolution and can handle 3x with ~90% GPU usage.

**Comment by hoverbike1** [comment]
please post this in here instead:
https://github.com/HolographicWings/TOTK-Mods-collection/issues/72
this is the hardware survey thread
